### ISSUE TITLE
Unable to Access Exhentai

### ISSUE THREAD

**Issue by CrownFox** [colin969/switch-reader#2]
Using the newest version I attempt to load the Exhentai domain, with an account that does have access to it, but it does not log in. It says "Logging in", then cuts to "Searching", then shows "No Results :(" with text at the bottom left stating "Not Logged In"

I can confirm that I can access Exhentai on the Chrome Browser on PC using the same account as is being used to connect on the Switch.

**Comment by colin969** [comment]
Try deleting the "cookies" folder from /switch/Reader/ and trying again. Make sure the host running web.py can connect to exhentai.org as well.

If that fails, would you mind dumping the "cookies" file from /switch/Reader/ here? Feel free to remove any personal information such as hostnames and hashed password tokens (although if it's not logging in I'd imagine they won't be there).

**Comment by colin969** [comment]
Hmm, don't know how I didn't catch this sooner - You could probably use v1.1 to login then switch to v1.2 to keep the cookies across, I was just about to put out a release so I'll make sure a fix is ready soon.

**Comment by CrownFox** [comment]
Alright, sounds good! Thank you! Definitely looking forward to the fix too!

I have a quick question related to the cookies

Do the cookies save amongst different modes? Like, if I access ExHentai, then switch to NHentai, can I switch back to ExHentai without re-entering my password for ExHentai?

**Comment by colin969** [comment]
Turns out it wasn't saving cookies when I moved the login function. 10/10

NHentai doesn't have login support yet so I wouldn't worry about being 'logged out' of Exhentai. You won't have to relog unless your auth becomes invalid or cookies is deleted. (And I'm hoping it doesn't have conflicting cookie names, since I can't separate it by hostname - The cookies are stored to the Proxy hostname)
